version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    ports:
      - "4001:80"
    depends_on:
      - backend
    restart: unless-stopped
